[package]
name = "lab2"
version = "0.1.0"
authors = ["Ivan Kalinin <i.kalinin@module.ru>"]
edition = "2018"

[[bin]]
name = "lab2"
path = "src/main.rs"

[dependencies]
hashbrown = "0.6"
num-bigint = "0.2"
rand = "0.7"
