[package]
name = "primes"
version = "0.1.0"
authors = ["Rexagon <reide740@gmail.com>"]
edition = "2018"


[dependencies]
hashbrown = "0.6"
num-bigint = "0.2"
rand = "0.7"
num_cpus = "1.0"
lazy_static = "1.4"
