[package]
name = "primes"
version = "0.1.0"
authors = ["Rexagon <reide740@gmail.com>"]
edition = "2018"


[dependencies]
num-bigint = { version = "0.2", features = ["rand"] }
num-traits = "0.2"
num-iter = "0.1"
rand = "0.5"
